version: '3.9'
services:
  mongodb:
    image: mongo:7.0
    environment:
      MONGO_INITDB_DATABASE: test_cf
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    command: mongod --bind_ip_all

volumes:
  mongodb_data:
